## Insider Threat Radar – Behavior Analytics for Employee Risk Prediction

### Supervised & Hybrid Modeling 

#### Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

import joblib

#### Load Data

In [2]:
data = pd.read_csv("../Dataset/anomaly_output.csv")
data.head()

,user,total_emails,total_attachments,avg_email_size,off_hour_emails,weekend_emails,employee_name,user_id,O,C,E,A,N,anomaly_label,anomaly_flag,anomaly_score
0,AAE0190,4711,1780,30020.394184,499,0,August Armando Evans,AAE0190,36,30,14,50,29,1,0,0.110730
1,AAF0535,480,364,30397.402083,1,0,Athena Amelia Foreman,AAF0535,17,21,36,33,31,1,0,0.119890
2,AAF0791,3012,0,29958.497676,377,0,Aladdin Abraham Foley,AAF0791,14,40,40,50,34,1,0,0.083532
3,AAL0706,336,145,29828.181548,54,0,April Alika Levy,AAL0706,37,14,28,13,25,1,0,0.137767
4,AAM0658,659,613,29895.532625,146,0,Abel Adam Morton,AAM0658,43,35,37,36,22,1,0,0.149285


#### Create Pseudo Labels

In [3]:
y = data['anomaly_flag']

feature_cols = [
    'total_emails',
    'total_attachments',
    'avg_email_size',
    'off_hour_emails',
    'weekend_emails',
    'O','C','E','A','N'
]

X = data[feature_cols]

#### Train Test Split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

### 🔵 RANDOM FOREST

In [5]:
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced'
)

rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

print("Random Forest Results")
print(confusion_matrix(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

Random Forest Results
[[196   0]
 [  3   1]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       196
           1       1.00      0.25      0.40         4

    accuracy                           0.98       200
   macro avg       0.99      0.62      0.70       200
weighted avg       0.99      0.98      0.98       200



### 🟣 GRADIENT BOOSTING

In [6]:
gb = GradientBoostingClassifier(random_state=42)

gb.fit(X_train, y_train)
gb_pred = gb.predict(X_test)

print("Gradient Boosting Results")
print(confusion_matrix(y_test, gb_pred))
print(classification_report(y_test, gb_pred))

Gradient Boosting Results
[[194   2]
 [  0   4]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       196
           1       0.67      1.00      0.80         4

    accuracy                           0.99       200
   macro avg       0.83      0.99      0.90       200
weighted avg       0.99      0.99      0.99       200



### 🔴 MLP (Neural Network)

In [7]:
mlp = MLPClassifier(
    hidden_layer_sizes=(64,32),
    max_iter=300,
    random_state=42
)

mlp.fit(X_train, y_train)
mlp_pred = mlp.predict(X_test)

print("MLP Results")
print(confusion_matrix(y_test, mlp_pred))
print(classification_report(y_test, mlp_pred))

MLP Results
[[193   3]
 [  0   4]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       196
           1       0.57      1.00      0.73         4

    accuracy                           0.98       200
   macro avg       0.79      0.99      0.86       200
weighted avg       0.99      0.98      0.99       200



#### Save Models

In [8]:
joblib.dump(rf, "../Model/random_forest.pkl")
joblib.dump(gb, "../Model/gradient_boosting.pkl")
joblib.dump(mlp, "../Model/mlp_model.pkl")

print("Models saved in Model/ folder ✅")

Models saved in Model/ folder ✅
